import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/primitives/index.ts',
    'src/primitives/Felt252/index.ts',
    'src/primitives/ContractAddress/index.ts',
    'src/primitives/ClassHash/index.ts',
    'src/primitives/StorageKey/index.ts',
    'src/primitives/ShortString/index.ts',
    'src/primitives/EthAddress/index.ts',
    'src/primitives/Address/index.ts',
    'src/primitives/BlockHeader/index.ts',
    'src/primitives/Block/index.ts',
    'src/primitives/Transaction/index.ts',
    'src/primitives/Receipt/index.ts',
    'src/primitives/Event/index.ts',
    'src/primitives/StateUpdate/index.ts',
    'src/primitives/FeeEstimate/index.ts',
    'src/primitives/Trace/index.ts',
    'src/crypto/index.ts',
    'src/serde/index.ts',
    'src/native/index.ts',
    'src/wasm/index.ts',
    'src/wasm-loader/index.ts',
    'src/jsonrpc/index.ts',
    'src/abi/index.ts',
    'src/transport/index.ts',
    'src/provider/index.ts',
    'src/utils/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  outDir: 'dist',
  // Mark FFI modules as external to avoid bundling errors
  external: [
    'bun:ffi',
    'koffi',
  ],
  // Ensure proper handling of conditional imports
  noExternal: [],
});
