/**
 * Starknet RPC Module
 *
 * Tree-shakeable JSON-RPC request builders for Starknet.
 */

export * as Rpc from './starknet/methods.js';
export * as RpcCodec from './rpc/index.js';

export type { BlockHashAndNumber } from './types.js';
export type { EventsFilter } from './types.js';

export type {
  RpcError,
  StarknetRpcErrorCode,
  BlockTag,
  BlockId,
  BlockStatus,
  BlockHeader,
  BlockHeaderWithCommitments,
  BlockWithTxHashes,
  PreConfirmedBlockWithTxHashes,
  BlockWithTxs,
  PreConfirmedBlockWithTxs,
  BlockWithReceipts,
  PreConfirmedBlockWithReceipts,
  BlockTransactionTrace,
  StateUpdate,
  PreConfirmedStateUpdate,
  StorageProof,
  ContractStorageDiffItem,
  DeployedContractItem,
  DeclaredClassItem,
  ReplacedClassItem,
  NonceUpdateItem,
  TransactionStatus,
  FunctionCall,
  SimulationFlag,
  FeeEstimate,
  ResourceBounds,
  ResourceBoundsMapping,
  MessageFeeEstimate,
  MsgFromL1,
  MessagesStatusResponse,
  SyncingStatus,
  EventsResponse,
  EmittedEvent,
  NewHead,
  TxnWithHash,
  TxnReceiptWithBlockInfo,
  TransactionTrace,
  SimulatedTransaction,
  BroadcastedTxn,
  BroadcastedInvokeTxn,
  BroadcastedDeclareTxn,
  BroadcastedDeployAccountTxn,
  ContractClass,
  AddInvokeTransactionResult,
  AddDeclareTransactionResult,
  AddDeployAccountTransactionResult,
  MessageStatus,
  PendingTransaction,
  TransactionStatusUpdate,
  WsTransactionReceipt,
  ReorgData,
  WsNotificationPayload,
  EventsSubscriptionParams,
  NewHeadsSubscriptionParams,
  PendingTransactionsSubscriptionParams,
  TransactionReceiptsSubscriptionParams,
  TxnFinalityStatusWithoutL1,
  ReceiptFinalityStatus,
} from './types.js';

// Rich types (branded primitives)
export type {
  RichResourcePrice,
  RichResourceBounds,
  RichResourceBoundsMapping,
  RichFeePayment,
  RichBlockHeader,
  RichBlockHeaderWithCommitments,
  RichBlockWithTxHashes,
  RichBlockWithTxs,
  RichBlockWithReceipts,
  RichTxnWithReceipt,
  RichInvokeTxnV0,
  RichInvokeTxnV1,
  RichInvokeTxnV3,
  RichInvokeTxn,
  RichL1HandlerTxn,
  RichDeclareTxnV0,
  RichDeclareTxnV1,
  RichDeclareTxnV2,
  RichDeclareTxnV3,
  RichDeclareTxn,
  RichDeployAccountTxnV1,
  RichDeployAccountTxnV3,
  RichDeployAccountTxn,
  RichTxn,
  RichTxnWithHash,
  RichEvent,
  RichMsgToL1,
  RichExecutionResources,
  RichTxnReceiptCommon,
  RichInvokeTxnReceipt,
  RichL1HandlerTxnReceipt,
  RichDeclareTxnReceipt,
  RichDeployAccountTxnReceipt,
  RichTxnReceipt,
  RichTxnReceiptWithBlockInfo,
  RichEmittedEvent,
  RichEventsResponse,
  RichContractStorageDiffItem,
  RichDeployedContractItem,
  RichDeclaredClassItem,
  RichReplacedClassItem,
  RichNonceUpdateItem,
  RichStateDiff,
  RichStateUpdate,
  RichFeeEstimate,
  RichOrderedEvent,
  RichOrderedMessage,
  RichInnerCallExecutionResources,
  RichFunctionInvocation,
  RichRevertibleFunctionInvocation,
  RichInvokeTxnTrace,
  RichDeclareTxnTrace,
  RichDeployAccountTxnTrace,
  RichL1HandlerTxnTrace,
  RichTransactionTrace,
  RichBlockTransactionTrace,
  RichSimulatedTransaction,
} from './rich.js';
